version: 2
updates:
- package-ecosystem: composer
  directories:
    - "/"
    - "/vendor-bin/csfixer"
    - "/vendor-bin/openapi-extractor"
    - "/vendor-bin/phpunit"
    - "/vendor-bin/psalm"
  commit-message:
    prefix: "ci"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  cooldown:
    default-days: 4
- package-ecosystem: npm
  directory: "/"
  commit-message:
    prefix: "build"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  cooldown:
    default-days: 4
    exclude:
      - "@nextcloud/*"
